name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Program arguments'
        required: false
        type: string

jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: java --show-version src/ListOpenJavaDevelopmentKits.java ${{ github.event.inputs.arguments }}
